language: python

sudo: false

services:
  - cassandra
  - rabbitmq

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  global:
    - CASSANDRA_PROTOCOL_VERSION=2
    - CASSANDRA_HOSTS=127.0.0.1

before_install:
- travis_retry wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH=/home/travis/miniconda/bin:$PATH
- conda update --yes conda

install:
- pip install -U pip
- conda install --yes numpy scipy matplotlib
- pip install -r requirements.txt
- pip install python-coveralls

script:
- coverage run -m unittest discover quantdsl -v

after_success:
- coveralls
