language: python
sudo: false

services:
  - cassandra
  - rabbitmq

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

env:
  global:
    - CASSANDRA_PROTOCOL_VERSION=2
    - CASSANDRA_HOSTS=127.0.0.1

install:
- pip install -U pip
- pip install -r requirements.txt
- pip install python-coveralls

script:
- coverage run -m unittest discover quantdsl -v

after_success:
- coveralls
