language: python

sudo: false

services:
  - rabbitmq

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
- travis_retry wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH=/home/travis/miniconda/bin:$PATH
- conda update --yes conda
- conda install --yes atlas numpy scipy matplotlib

install:
- pip install -U pip
- pip install .[test]
- pip install python-coveralls

script:
- coverage run -m unittest discover quantdsl.tests -v

after_success:
- coveralls
