language: python
python:
  - "2.7_with_system_site_packages"
install: pip install -r requirements.txt --use-mirrors
script: python -m unittest quantdsl.test 
before_install:
 - sudo apt-get install -qq python-numpy python-scipy
